import { Inter } from "next/font/google";
import "./globals.css";
import { Header, Footer } from "@/components";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <link href="https://fonts.googleapis.com/css2?family=Urbanist:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"></link> */}
      <body className={inter.className + " bg-black"}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
